l# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [ ]:
import numpy as np

In [ ]:
np.random.randint(0, 20, size = (4, 7))

array([[ 1, 18,  2,  7, 19,  1,  9],
       [ 5,  2,  2, 16,  6,  8, 18],
       [16,  0, 15,  1, 15,  9,  5],
       [12,  3,  9,  9,  3,  5, 10]])

In [ ]:
data = np.random.uniform(0, 20, size = (4, 7))
print(data)
(data-np.min(data))/(np.max(data)-np.min(data))

[[ 9.65210085 14.29429956 13.80916237  3.87677485 15.79085319  7.71327526
   9.06102786]
 [14.29353185 12.0982555  15.56700058  6.43420773  9.88843517 19.1072886
   0.50213662]
 [12.22117567  4.40180819  3.01188655  3.00151326  9.85165729  4.63169857
  12.10098898]
 [ 2.33095243 12.37717128 15.15141479 10.36587093  6.3523616  16.50630985
  10.41034337]]


array([[0.49179734, 0.7413088 , 0.71523338, 0.18138192, 0.8217464 ,
        0.38758827, 0.46002802],
       [0.74126754, 0.62327461, 0.80971464, 0.31884024, 0.50449997,
        1.        , 0.        ],
       [0.62988139, 0.2096017 , 0.13489543, 0.13433788, 0.50252321,
        0.22195798, 0.62342153],
       [0.0982962 , 0.63826593, 0.78737751, 0.53016145, 0.31444113,
        0.86020116, 0.53255178]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
np.random.randint(0, 10, size = (8, 10))

array([[0, 6, 2, 4, 5, 3, 3, 5, 5, 8],
       [4, 7, 0, 3, 3, 8, 8, 5, 9, 4],
       [5, 6, 6, 9, 0, 8, 8, 7, 4, 4],
       [6, 1, 9, 0, 0, 4, 5, 4, 7, 3],
       [9, 2, 8, 0, 4, 4, 9, 5, 9, 9],
       [9, 6, 0, 1, 6, 1, 1, 8, 0, 1],
       [1, 3, 9, 1, 2, 5, 7, 6, 8, 9],
       [2, 9, 4, 7, 4, 3, 8, 4, 2, 8]])

In [ ]:
arr = np.random.randint(0, 10, size = (8, 10))
print(arr)
print("Row Index",np.argmin(np.sum(arr, axis=1)))
arr[np.argmin(np.sum(arr, axis=1))]

[[5 2 6 7 4 2 2 0 3 9]
 [8 5 4 7 4 4 5 2 9 9]
 [5 3 9 8 4 7 5 2 2 8]
 [5 2 4 8 6 1 8 8 5 9]
 [3 9 1 7 4 6 8 0 8 0]
 [9 4 0 6 9 8 8 3 5 7]
 [4 7 2 2 5 8 1 4 0 5]
 [2 7 2 3 9 7 2 5 2 2]]
Row Index 6


array([4, 7, 2, 2, 5, 8, 1, 4, 0, 5])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [ ]:
point_1 = np.random.randint(0, 20, size=5)
point_2 = np.random.randint(0, 20, size=5)
print(point_1)
print(point_2)
#first way
square = np.square(point_1 - point_2)
sum_square = np.sum(square)
print(np.sqrt(sum_square))
#second way
distance = np.linalg.norm(point_1-point_2)
print(distance)

[ 7 18 18  9  5]
[ 9  4  8 15 12]
19.621416870348583
19.621416870348583


In [ ]:
import matplotlib.pyplot as pl
from mpl_toolkits.mplot3d import Axes3D

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [ ]:
a = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
b = np.array([[3, -1], [2, 1]])
c = np.array([[7, 21], [11, 8], [8, 4]])
#решение: x = a^-1*(-c)*b^-1

x0 = np.matmul(np.linalg.inv(a),(-c))
print(x0)
x =  np.matmul(x0,np.linalg.inv(b))
print(x)

[[ 3. -1.]
 [-4.  3.]
 [ 1. -7.]]
[[ 1.00000000e+00  5.32907052e-16]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
data = np.loadtxt("/content/drive/MyDrive/L/minutes_n_ingredients.csv", delimiter=',', skiprows=1, dtype=np.int32)
# first 5 rows
print(data[0:5, :])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


In [ ]:
d1 = data.copy()

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [ ]:
#делаем срез массива, извлекаем все кроме первого массива
sliced = data[:,1:]
# находим среднее по столбцам среза
print(np.mean(sliced,axis=0))
# находим минимум по столбцам среза
print(np.min(sliced, axis=0))
# находим максимум по столбцам среза
print(np.max(sliced, axis=0))
# находим медиану по столбцам среза
print(np.median(sliced, axis=0))

[2.16010017e+04 9.05528000e+00]
[0 1]
[2147483647         39]
[40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$.

In [ ]:
np.clip(data[:, 1],0,np.quantile(data[:, 1],0.75,method='higher'))

array([60, 25, 10, ..., 65,  5, 65], dtype=int32)

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [ ]:
print(np.count_nonzero (d1[:, 1] == 0))

479


In [ ]:
print(np.place(data, data==0, 1))

None


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [ ]:
#уникальные рецепты - это рецепты, у которых не повторяются минуты и количество ингредиентов
len(np.unique(sliced, axis=0))

4183

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [ ]:
print(np.unique(data[:, 2], axis=0))
print(np.unique(data[:, 2], axis=0).size)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]
37


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [ ]:
data2 = data[np.where(data[:, 2] <= 5)]
print(data2)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [ ]:
A = data[:, 1]
B = data[:, 2]
C = B/A
print(C)
data_c = [C]
sliced = data_c[:]
print(np.max(sliced,axis=1))

[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]
[24.]


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей
продолжительностью

In [ ]:
d1_sorted_desc = d1[d1[:, 1]. argsort ()[::-1]]
print(d1_sorted_desc)

[[    261647 2147483647          8]
 [    216215     259260          7]
 [    425681     259205          2]
 ...
 [     50748          0         12]
 [      5354          0          8]
 [      4896          0         14]]


In [ ]:
x = np.mean(d1_sorted_desc[:100,2], axis=0)
x

6.61

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [ ]:
index = np.random.randint(d1.shape[0], size=10)
random_rows = d1[index, :]
print(random_rows)

[[ 38502    250      5]
 [277707     60      8]
 [ 87534     25      8]
 [ 69143     25      6]
 [126063     80     12]
 [197945     20      3]
 [ 65968     75     10]
 [ 17206     10      6]
 [362849     35     14]
 [293574    150      7]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [ ]:
sr1 =  data[:,2:]
r = np.mean(sr1,axis=0)
print(r) # cреднее значение инградиентов массива
x = np.count_nonzero(sr1[:,:2:] <= r[:])
print(x) # количество рецептов меньше среднего
s = np.count_nonzero(sr1)
print(s) # количество всего рецептов по массиву (100%)
percent = x*100/s
print(percent) # Ответ

[9.05528]
58802
100000
58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [ ]:
h1 = d1.copy()

In [ ]:
now1 = h1[(h1[:, 1] <= 20) & (h1[:, 2] <= 5)]
now1

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 60756,     15,      5],
       [128811,     15,      4],
       [370915,      5,      4]], dtype=int32)

In [ ]:
now1.shape

(9552, 3)

In [ ]:
h2 = np.zeros((9552,1))
h2

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [ ]:
h5 = np.hstack((now1, h2))
h5

array([[4.46597e+05, 1.50000e+01, 5.00000e+00, 0.00000e+00],
       [2.04134e+05, 5.00000e+00, 3.00000e+00, 0.00000e+00],
       [2.56230e+04, 6.00000e+00, 4.00000e+00, 0.00000e+00],
       ...,
       [6.07560e+04, 1.50000e+01, 5.00000e+00, 0.00000e+00],
       [1.28811e+05, 1.50000e+01, 4.00000e+00, 0.00000e+00],
       [3.70915e+05, 5.00000e+00, 4.00000e+00, 0.00000e+00]])

13. Выведите процент "простых" рецептов в датасете

In [ ]:
s1 = np.count_nonzero(now1[::,2]) # количество простых рецептов
s3 = np.count_nonzero(d1[:,2]) # всего
resultat = s1*100/s3
print('Простых рецептов:', resultat,'%')

Простых рецептов: 9.552 %


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [ ]:
v1 = h1[(h1[:, 1] < 10)] # короткий рецепт
v2 = h1[(h1[:, 1] >= 10) & (h1[:, 1] < 20)]  # стандартный рецепт
v3 = h1[(h1[:, 1] >= 20)] # длинный рецепт
print(v1.shape, v2.shape, v3.shape)
v1

(7588, 3) (12661, 3) (79751, 3)


array([[ 67660,      5,      6],
       [366174,      7,      9],
       [204134,      5,      3],
       ...,
       [420725,      5,      3],
       [  4747,      0,      9],
       [370915,      5,      4]], dtype=int32)

In [ ]:
n = {'1': 'v1','2':'v2','3': 'v3'}
n

{'1': 'v1', '2': 'v2', '3': 'v3'}

In [ ]:
v2 = v1
v3 = v2
v1 = v3
print(v1.shape, v2.shape, v3.shape)
v2

(7588, 3) (7588, 3) (7588, 3)


array([[ 67660,      5,      6],
       [366174,      7,      9],
       [204134,      5,      3],
       ...,
       [420725,      5,      3],
       [  4747,      0,      9],
       [370915,      5,      4]], dtype=int32)

In [ ]:
result = np.stack((v1, v2, v3), axis = 0)
print(result)

[[[ 67660      5      6]
  [366174      7      9]
  [204134      5      3]
  ...
  [420725      5      3]
  [  4747      0      9]
  [370915      5      4]]

 [[ 67660      5      6]
  [366174      7      9]
  [204134      5      3]
  ...
  [420725      5      3]
  [  4747      0      9]
  [370915      5      4]]

 [[ 67660      5      6]
  [366174      7      9]
  [204134      5      3]
  ...
  [420725      5      3]
  [  4747      0      9]
  [370915      5      4]]]
