<a href="https://colab.research.google.com/github/ms236566/-/blob/main/%D0%9B%D0%B0%D0%B1%D1%80%D0%B0%D0%B1_numpy_%D0%94%D0%9F%D0%9823_1_%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B8%D1%87%D0%B5%D0%B2%D0%B0_%D0%9E%D0%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

l# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [ ]:
import numpy as np

In [ ]:
np.random.randint(0, 20, size = (4, 7))

array([[ 9, 12,  6, 16,  2,  4,  0],
       [10, 19, 11, 16,  2, 17, 19],
       [ 5, 16,  6, 11, 16,  2, 11],
       [18, 14, 13,  3, 11,  1, 16]])

In [ ]:
data = np.random.uniform(0, 20, size = (4, 7))
print(data)
(data-np.min(data))/(np.max(data)-np.min(data))

[[ 7.34122918  9.51754665  9.88276053 12.57832782 18.24180714  3.82791777
  18.04527595]
 [ 7.2841805  17.52313454  5.4616427  14.91150231  1.62659707 15.13165791
   4.12246199]
 [16.75975776 15.86213934 10.61214619  0.04490242 16.22056876  8.62023501
   8.14663919]
 [ 9.73210777  4.04766465 14.04149525  4.78209797 19.1308378  19.4211117
  16.91708703]]


array([[0.3765611 , 0.48888016, 0.50772873, 0.6468461 , 0.93913647,
        0.19524022, 0.92899355],
       [0.37361684, 0.902046  , 0.27955624, 0.76726049, 0.08163076,
        0.77862265, 0.21044155],
       [0.86264837, 0.81632257, 0.54537209, 0.        , 0.834821  ,
        0.44257019, 0.41812806],
       [0.49995359, 0.20658129, 0.72235971, 0.24448516, 0.98501906,
        1.        , 0.87076808]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
np.random.randint(0, 10, size = (8, 10))

array([[8, 9, 5, 7, 0, 9, 5, 3, 7, 9],
       [5, 4, 0, 5, 9, 4, 9, 7, 4, 7],
       [9, 3, 5, 8, 6, 7, 4, 7, 7, 5],
       [4, 6, 5, 7, 4, 9, 1, 0, 4, 6],
       [9, 6, 4, 3, 1, 3, 7, 4, 4, 6],
       [4, 9, 3, 6, 6, 5, 2, 2, 6, 4],
       [3, 6, 3, 0, 7, 7, 7, 3, 1, 5],
       [9, 6, 0, 1, 8, 7, 6, 5, 1, 7]])

In [ ]:
arr = np.random.randint(0, 10, size = (8, 10))
print(arr)
print("Row Index",np.argmin(np.sum(arr, axis=1)))
arr[np.argmin(np.sum(arr, axis=1))]

[[0 1 9 6 8 9 9 7 3 5]
 [6 7 8 3 5 8 2 3 3 6]
 [1 0 6 5 0 7 4 1 4 1]
 [5 6 2 2 0 0 0 3 8 0]
 [8 8 0 6 1 2 9 1 0 4]
 [3 1 9 1 0 3 0 4 6 9]
 [0 9 6 6 1 5 8 4 0 3]
 [6 0 5 3 0 0 7 3 1 6]]
Row Index 3


array([5, 6, 2, 2, 0, 0, 0, 3, 8, 0])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [ ]:
point_1 = np.random.randint(0, 20, size=5)
point_2 = np.random.randint(0, 20, size=5)
print(point_1)
print(point_2)
#first way
square = np.square(point_1 - point_2)
sum_square = np.sum(square)
print(np.sqrt(sum_square))
#second way
distance = np.linalg.norm(point_1-point_2)
print(distance)

[10 11  4  6  7]
[16  2  6 19 16]
19.261360284258224
19.261360284258224


In [ ]:
import matplotlib.pyplot as pl
from mpl_toolkits.mplot3d import Axes3D

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [ ]:
a = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
b = np.array([[3, -1], [2, 1]])
c = np.array([[7, 21], [11, 8], [8, 4]])
#решение: x = a^-1*(-c)*b^-1

x0 = np.matmul(np.linalg.inv(a),(-c))
print(x0)
x =  np.matmul(x0,np.linalg.inv(b))
print(x)

[[ 3. -1.]
 [-4.  3.]
 [ 1. -7.]]
[[ 1.00000000e+00  5.32907052e-16]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [42]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [43]:
data = np.loadtxt("/content/drive/MyDrive/L/minutes_n_ingredients.csv", delimiter=',', skiprows=1, dtype=np.int32)
# first 5 rows
print(data[0:5, :])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


In [44]:
d1 = data.copy()

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [45]:
#делаем срез массива, извлекаем все кроме первого массива
sliced = data[:,1:]
# находим среднее по столбцам среза
print(np.mean(sliced,axis=0))
# находим минимум по столбцам среза
print(np.min(sliced, axis=0))
# находим максимум по столбцам среза
print(np.max(sliced, axis=0))
# находим медиану по столбцам среза
print(np.median(sliced, axis=0))

[2.16010017e+04 9.05528000e+00]
[0 1]
[2147483647         39]
[40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$.

In [46]:
np.clip(data[:, 1],0,np.quantile(data[:, 1],0.75,method='higher'))

array([60, 25, 10, ..., 65,  5, 65], dtype=int32)

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [47]:
print(np.count_nonzero (d1[:, 1] == 0))

479


In [48]:
print(np.place(data, data==0, 1))

None


In [49]:
#Проверка
print(np.count_nonzero (data[:, 1] == 1)-(np.count_nonzero (d1[:, 1] == 1)))

479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [50]:
#уникальные рецепты - это рецепты, у которых не повторяются минуты и количество ингредиентов
len(np.unique(sliced, axis=0))

4183

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [51]:
print(np.unique(data[:, 2], axis=0))
print(np.unique(data[:, 2], axis=0).size)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]
37


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [52]:
data2 = data[np.where(data[:, 2] <= 5)]
print(data2)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [53]:
A = data[:, 1]
B = data[:, 2]
C = B/A
print(C)
data_c = [C]
sliced = data_c[:]
print(np.max(sliced,axis=1))

[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]
[24.]


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей
продолжительностью

In [54]:
d1_sorted_desc = d1[d1[:, 1]. argsort ()[::-1]]
print(d1_sorted_desc)

[[    261647 2147483647          8]
 [    216215     259260          7]
 [    425681     259205          2]
 ...
 [     50748          0         12]
 [      5354          0          8]
 [      4896          0         14]]


In [56]:
x = np.mean(d1_sorted_desc[:100,2], axis=0)
x

6.61

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [57]:
index = np.random.randint(d1.shape[0], size=10)
random_rows = d1[index, :]
print(random_rows)

[[222397      6      3]
 [317907     35      7]
 [389560     15      5]
 [268410     70      7]
 [ 27510     65     14]
 [115414     65     10]
 [413672     90     18]
 [260354     70      6]
 [105591     50      5]
 [ 23736     65      7]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [163]:
sr1 =  data[:,2:]
r = np.mean(sr1,axis=0)
print(r) # cреднее значение инградиентов массива
x = np.count_nonzero(sr1[:,:2:] <= r[:])
print(x) # количество рецептов меньше среднего
s = np.count_nonzero(sr1)
print(s) # количество всего рецептов по массиву (100%)
percent = x*100/s
print(percent) # Ответ

[9.05528]
58802
100000
58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [146]:
now1 = d1[(data[:, 1] <= 20) & (data[:, 2] <= 5)]
now1

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 60756,     15,      5],
       [128811,     15,      4],
       [370915,      5,      4]], dtype=int32)

In [184]:
now2 = d1[~(data[:, 1] <= 20) | ~(data[:, 2] <= 5)]
now2

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [287943,     85,     15],
       [498432,     65,     15],
       [ 81993,    140,     14]], dtype=int32)

13. Выведите процент "простых" рецептов в датасете

In [201]:
s1 = np.count_nonzero(now1[::,2]) # количество простых рецептов
s2 = np.count_nonzero(now2[:,2]) # количество не простых рецептов
s3 = np.count_nonzero(d1[:,2]) # всего
resultat = s1*100/s3
print('Простых рецептов:', resultat,'%')

Простых рецептов: 9.552 %


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

оно мудреное очень))
я сначала отдельным столбцом вычислил группу
если больше 10, то плюс 1, если больше 20, то еще плюс 1
потом через hstack присобачил ее к копии массива
через unique нашел значения групп и количество в каждой
взял минимальное кол-во в группе
потом соорудил нулевой массив нужной формы и дальше его уже заполнял